//HintName: TestMethodCommand.g.cs
// <auto-generated />
#nullable enable
using System;
namespace idee5.SoureGeneratorTests {
	public class TestMethodCommand {
		public int Para1 { get; }
		public idee5.Common.DateTimeRange Para2 { get; }

		/// <summary>
		/// Create a new command.
		/// </summary>
		/// <param name="para1"></param>
		/// <param name="para2">42 <see cref="T:System.StackOverflowException" /></param>
		public TestMethodCommand(int para1, idee5.Common.DateTimeRange para2) {
			Para1 = para1;
			Para2 = para2;
		}
	}
}
