//HintName: TestMethodCommandHandler.g.cs
// <auto-generated />
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;

namespace idee5.SoureGeneratorTests {
    /// <inheritdoc/>
    public class TestMethodCommandHandler : ICommandHandler<TestMethodCommand> {

        /// <inheritdoc/>
        public TestMethodCommandHandler(ISession session) : base(session) {
        }
        /// <inheritdoc/>
        public override async Task Handle(TestMethodCommand command) {
            if (command is null) throw new ArgumentNullException(nameof(command));

            Console.WriteLine("Method TestMethod with parameters command.Para1, command.Para2 would be invoked.");
        }
    }
}
