//HintName: ParamerlessMethodCommand.g.cs
// <auto-generated />
#nullable enable
using System;
namespace idee5.SoureGeneratorTests {
	public class ParamerlessMethodCommand {

		/// <summary>
		/// Create a new command.
		/// </summary>
		public ParamerlessMethodCommand() {
		}
	}
}
