//HintName: ParamerlessMethodCommandHandler.g.cs
// <auto-generated />
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;

namespace idee5.SoureGeneratorTests {
    /// <inheritdoc/>
    public class ParamerlessMethodCommandHandler : ICommandHandler<ParamerlessMethodCommand> {

        /// <inheritdoc/>
        public ParamerlessMethodCommandHandler(ISession session) : base(session) {
        }
        /// <inheritdoc/>
        public override async Task Handle(ParamerlessMethodCommand command) {
            if (command is null) throw new ArgumentNullException(nameof(command));

            Console.WriteLine("Method ParamerlessMethod with parameters  would be invoked.");
        }
    }
}
