# https://github.com/alirezanet/publish-nuget
name: Build, test & publish
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: |
          dotnet nuget add source https://nuget.telerik.com/v3/index.json -n MyTelerikFeed -u api-key -p ${{secrets.TELERIK_API_KEY}} --store-password-in-clear-text
          dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --filter FullyQualifiedName\!~NtpClientTests --configuration Release --no-build --verbosity normal
    - name: Pack
      uses: alirezanet/publish-nuget@v3.1.0
      with:
       PROJECT_FILE_PATH: idee5.Common/idee5.Common.csproj
       NUGET_KEY: ${{secrets.NUGET_API_KEY}}
       NO_BUILD: true
    - name: Publish data lib
      uses: alirezanet/publish-nuget@v3.1.0
      with:
       PROJECT_FILE_PATH: idee5.Common.Data/idee5.Common.Data.csproj
       NUGET_KEY: ${{secrets.NUGET_API_KEY}}
       NO_BUILD: true
    - name: Publish source generators
      uses: alirezanet/publish-nuget@v3.1.0
      with:
       PROJECT_FILE_PATH: idee5.SourceGenerators/idee5.SourceGenerators.csproj
       NUGET_KEY: ${{secrets.NUGET_API_KEY}}
       NO_BUILD: true
